describe('Dynamic Test Suite', () => {

  before(() => {
    cy.visit('https://hospersa.propay.co.za/application');
  });

  it('fills out the form and submits it', () => {

    cy.get('[name="viewport"]').type('Sample Text');
    cy.get('[name="csrf-token"]').type('Sample Text');
    cy.get('link').type('Sample Text');
    cy.get('#app').type('Sample Text');
    cy.get('#register_holder').type('Sample Text');
    cy.get('#registerFrm').type('Sample Text');
    cy.get('[name="_token"]').type('Sample Text');
    cy.get('#product_start_date').type('Sample Text');
    cy.get('#birth_date').type('Sample Text');
    cy.get('#bank_id').type('Sample Text');
    cy.get('#branch_id').type('Sample Text');
    cy.get('#branch_code').type('Sample Text');
    cy.get('#account_holder').type('Sample Text');
    cy.get('#account_number').type('Sample Text');
    cy.get('#account_type').type('Sample Text');
    cy.get('#firstname').type('John');
    cy.get('#initials').type('Sample Text');
    cy.get('#surname').type('John');
    cy.get('#citizen_holder').type('Sample Text');
    cy.get('[name="citizen"]').type('Sample Text');
    cy.get('[name="citizen"]').type('Sample Text');
    cy.get('#id_number_holder').type('Sample Text');
    cy.get('#id_number').type('Sample Text');
    cy.get('#passportOption').type('Sample Text');
    cy.get('#passport_number_holder').type('Sample Text');
    cy.get('#passport_no').type('Sample Text');
    cy.get('#country_id').type('Sample Text');
    cy.get('#gender_id').type('Sample Text');
    cy.get('#cell_holder').type('0812345678');
    cy.get('#cell').type('0812345678');
    cy.get('#email_holder').type('johndoe@example.com');
    cy.get('#email').type('johndoe@example.com');
    cy.get('#password').type('SecurePassword123!');
    cy.get('#password-confirm').type('SecurePassword123!');
    cy.get('#member_category_id').type('Sample Text');
    cy.get('#employment_type').type('Sample Text');
    cy.get('#employment_details_holder').type('Sample Text');
    cy.get('#employer_id').type('Sample Text');
    cy.get('#occupation').type('Sample Text');
    cy.get('#employee_number_holder').type('Sample Text');
    cy.get('#employee_number_public').type('Sample Text');
    cy.get('#payment_method_id').type('Sample Text');
    cy.get('#paymentDetailsLinkContainer').type('Sample Text');
    cy.get('#paymentDetailsLink').type('Sample Text');
    cy.get('#readConsentBtn').type('Sample Text');
    cy.get('#research_consent_yes').type('Sample Text');
    cy.get('#research_consent_no').type('Sample Text');
    cy.get('#cancel_current_union_yes').type('Sample Text');
    cy.get('#cancel_current_union_no').type('Sample Text');
    cy.get('#autocomplete').type('Sample Text');
    cy.get('#postalDiv').type('Sample Text');
    cy.get('#address1').type('Sample Text');
    cy.get('#address2').type('Sample Text');
    cy.get('#address3').type('Sample Text');
    cy.get('#address4').type('Sample Text');
    cy.get('#address5').type('Sample Text');
    cy.get('#postal_province').type('Sample Text');
    cy.get('#readTCsBtn').type('Sample Text');
    cy.get('#term_and_conditions').type('Sample Text');
    cy.get('#readDisclaimerBtn').type('Sample Text');
    cy.get('#registerBtnHolder').type('Sample Text');
    cy.get('#registerBtn').type('Sample Text');
    cy.get('#myDisclaimer').type('Sample Text');
    cy.get('button').type('Sample Text');
    cy.get('#myModalLabel').type('Sample Text');
    cy.get('#myDisclaimerCloseModalBtn').type('Sample Text');
    cy.get('#myConsent').type('Sample Text');
    cy.get('button').type('Sample Text');
    cy.get('#myModalLabel').type('Sample Text');
    cy.get('#myConsentCloseModalBtn').type('Sample Text');
    cy.get('#myTermsAndConditions').type('Sample Text');
    cy.get('button').type('Sample Text');
    cy.get('#myModalLabel').type('Sample Text');
    cy.get('#public_member_type').type('Sample Text');
    cy.get('#member_names').type('John');
    cy.get('#public_product_price').type('Sample Text');
    cy.get('#start_date').type('Sample Text');
    cy.get('#private_member_type').type('Sample Text');
    cy.get('#private_product_price').type('Sample Text');
    cy.get('#myTermsAndConditionsCloseModalBtn').type('Sample Text');
    cy.get('#clientTCs').type('Sample Text');
    cy.get('button').type('Sample Text');
    cy.get('#myModalLabel').type('Sample Text');
    cy.get('#clientTcsCloseModalBtn').type('Sample Text');
    cy.get('#paymentDetailModal').type('Sample Text');
    cy.get('#registerPaymentDetailsForm').type('Sample Text');
    cy.get('[name="_token"]').type('Sample Text');
    cy.get('#paymentToken').type('Sample Text');
    cy.get('button').type('Sample Text');
    cy.get('#myModalLabel').type('Sample Text');
    cy.get('#method').type('Sample Text');
    cy.get('#doDisplayDiv').type('Sample Text');
    cy.get('#debitOrderDiv').type('Sample Text');
    cy.get('#bank').type('Sample Text');
    cy.get('#branch').type('Sample Text');
    cy.get('#bcode').type('Sample Text');
    cy.get('#holder').type('Sample Text');
    cy.get('#number').type('Sample Text');
    cy.get('#type').type('Sample Text');
    cy.get('#paymentDetailCloseModalBtn').type('Sample Text');
    cy.get('#paymentDetailDoneModalBtn').type('Sample Text');
    cy.get('script').type('Sample Text');
    cy.get('script').type('Sample Text');
    cy.get('script').type('Sample Text');
    cy.get('script').type('Sample Text');

  });
});
